version: "3.5"

services:
  web-02:
    build:
      context: ./lesson-02
    container_name: fw-web-02
    deploy:
      labels:
        com.fluentweb.lesson-02: "Hello world"
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy: 
        condition: on-failure
    networks: 
      - fw-elb
    ports:
      - "2000:80"
      - "2001:443"
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./lesson-02/build/public:/var/www/html
      - ./lesson-02/root/etc/nginx/conf.d:/etc/nginx/conf.d
    networks:
      fw-elb: 
      
  web-03:
    build:
      context: ./lesson-03
    container_name: fw-web-03
    deploy:
      labels:
        com.fluentweb.lesson-03: "Fluent Website"
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy: 
        condition: on-failure
    networks: 
      - fw-elb
    ports:
      - "3000:80"
      - "3001:443"
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./lesson-03/build/public:/var/www/html
      - ./lesson-03/root/etc/nginx/conf.d:/etc/nginx/conf.d
networks:
  fw-elb: 