version: "3.5"

services:
  web-02:
    build:
      context: ./lesson-two
    container_name: fw-web-02
    deploy:
      labels:
        com.fluentweb.lesson-two: "Hello world"
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy: 
        condition: on-failure
    networks: 
      - fw-elb
    ports:
      - "2000:80"
      - "2001:443"
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./lesson-two/build/public:/var/www/html
      - ./lesson-two/root/etc/nginx/conf.d:/etc/nginx/conf.d
    networks:
      fw-elb: 
      
  web-03:
    build:
      context: ./lesson-three
    container_name: fw-web-03
    deploy:
      labels:
        com.fluentweb.lesson-three: "Fluent Website"
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy: 
        condition: on-failure
    networks: 
      - fw-elb
    ports:
      - "3000:80"
      - "3001:443"
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./lesson-three/build/public:/var/www/html
      - ./lesson-three/root/etc/nginx/conf.d:/etc/nginx/conf.d
networks:
  fw-elb: 